Tysserand:
  Nodes directory: /home/owen.griere/Desktop/MOSNA_GUI/test/patient_sample_folder
  Patient column name: patient
  Sample column name: chunk
  Extension: parquet
  X coordinates column: x_centroid
  Y coordinates column: y_centroid
  Phenotype column: phenotype
  Edges method: delaunay
  Min neighbors: 3
  CPU: 20
Assortativity:
  Network directory: Default
  Phenotype column: phenotype
  Patient column name: patient
  Sample column name: chunk
  Extension: parquet
  Index: index
  Number of shuffle: 20
  Randomization diagnostic: false
Niche Analysis:
  Network directory: Default
  Saving directory: niche_1
  Extension: parquet
  Patient column name: patient
  Sample column name: chunk
  Processing method: Per sample
  Niches method: NAS
  Phenotype column: phenotype
  Column to aggregate: phenotype
  Plot Network: false
  X coordinates column for niches: null
  Y coordinates column for niches: null
  CPU: 20
  Aggregated nodes:
    order: '1'
    stat_funcs: np.mean,np.std
    stat_names: [mean, std]
    clusterer_type: gmm
    n_clusters: 8
    reducer_type: umap
    metric: manhattan
    resolution: 0.05
    n_neighbors: 20
    min_dist: 0.0
    dim_clust: 3
    min_cluster_size: 100
    k_cluster: 20
    normalize: all
  Per sample:
    order: '1'
    stat_funcs: np.mean,np.std
    stat_names: [mean, std]
    clusterer_type: gmm
    n_clusters: 6
    reducer_type: umap
    metric: manhattan
    resolution: 0.001
    n_neighbors: 50
    min_dist: 0.0
    dim_clust: 3
    min_cluster_size: 1
    k_cluster: 20
    normalize: all
