silent: false
add_pheno: true
pheno_dir: data/processed/Bram_data/phenotypes
IF_import:
  present_in: true
  directory_path: data/processed/Bram_data/IF_merged_by_patient/
  panel: C2
  path_encoding_patient: null
  path_file_to_patient: data/processed/Bram_data/file_to_patient/IF_file_to_patient.csv
  columns_to_drop: null
  layer_columns: ROI_ID
  patient_columns: Patient_ID
  phenotypes: null
  marker_columns: '3:5'
  cell_id_columns: 0
  spatial_columns: '1:2'
  re_index: false
IMC_import:
  present_in: false
  directory_path: data/processed/Bram_data/acquired_csv_files/
  path_encoding_patient: data/processed/Bram_data/alphabetical_encoding_patient_ID/IMC_patient_id_encoding.csv
  path_file_to_patient: data/processed/Bram_data/file_to_patient/IMC_file_to_patient.csv
  columns_to_drop: 'Unnamed: 0'
  layer_columns: null
  patient_columns: null
  phenotypes: null
  marker_columns: 0:19 21:33
  cell_id_columns: 20
  spatial_columns: '34:35'
  re_index: true
