Tysserand:
  Nodes directory: /home/owen.griere/Desktop/Xenium_analysis/nodes_mapped/mes_chunks_4/nodes
  Patient column name: patient
  Sample column name: chunk
  Extension: parquet
  X coordinates column: x_centroid
  Y coordinates column: y_centroid
  Phenotype column: phenotype
  Edges method: delaunay
  Min neighbors: 3
  CPU: 20
Assortativity:
  Network directory: /home/owen.griere/Desktop/Xenium_analysis/nodes_mapped/mes_chunks_4
  Phenotype column: null
  Patient column name: patient
  Sample column name: chunk
  Extension: parquet
  Index: index
  Number of shuffle: 50
  Randomization diagnostic: false
Niche Analysis:
  Network directory: /home/owen.griere/Desktop/Xenium_analysis/nodes_mapped/mes_chunks_4
  Saving directory: niche_1
  Extension: parquet
  Patient column name: patient
  Sample column name: chunk
  Processing method: Aggregated nodes
  Niches method: NAS
  Phenotype column: null
  Column to aggregate: null
  Plot Network: true
  X coordinates column for niches: null
  Y coordinates column for niches: null
  CPU: 20
  Aggregated nodes:
    order: '1'
    stat_funcs: np.mean,np.std
    stat_names: [mean, std]
    reducer_type: umap
    dim_clust: 3
    n_neighbors: 20
    metric: cosine
    min_dist: 0.0
    clusterer_type: gmm
    k_cluster: 20
    n_clusters: 7
    resolution: 0.05
    min_cluster_size: 100
    normalize: all
  Per sample:
    order: '1'
    stat_funcs: np.mean,np.std
    stat_names: [mean, std]
    reducer_type: umap
    dim_clust: 3
    n_neighbors: 20
    metric: cosine
    min_dist: 0.0
    clusterer_type: gmm
    k_cluster: 20
    n_clusters: 7
    resolution: 0.05
    min_cluster_size: 100
    normalize: all
