standard:
  saving: True
  output_dir: pandas_data

IMC_import:
  present_in: True
  directory_path: data/processed/Bram_data/acquired_csv_files/*.csv
  path_encoding_patient: data/processed/Bram_data/alphabetical_encoding_patient_ID/IMC_patient_id_encoding.csv
  path_file_to_patient: data/processed/Bram_data/file_to_patient/IMC_file_to_patient.csv
  normalize: True
  re_index: True
  there_is_duplicata: False

  columns_to_drop: ['Unnamed: 0']
  marker_columns: "0:19 21:33"
  cell_id_columns: 20
  spatial_columns: "34:35"
  other_columns: 
  other_columns_name: 

IF_import:
  present_in: True
  directory_path: data/processed/Bram_data/IF_merged_by_patient/*.csv
  path_encoding_patient: 
  path_file_to_patient: data/processed/Bram_data/file_to_patient/IF_file_to_patient.csv
  normalize: False
  re_index: False
  there_is_duplicata: True

  columns_to_drop: 
  marker_columns: "3:6"
  cell_id_columns: 0
  spatial_columns: "1:2"
  other_columns: 8
  other_columns_name: ['ROI_ID']

test:
  partial: False
  which_file_if_partial: 
  directory_to_test: pandas_data/*.parquet
  test_directory: pandas_data/test/*.csv

tysserand:
  k_neighbors_phenograph: 30
  primary_metric_phenograph: 'minkowski'
  method_tysserand: 'delaunay'
  min_neighbors: 3
