name: CI

on:
  push:
  pull_request:

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du dépôt
        uses: actions/checkout@v4

      - name: Installation de Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true

      - name: Libérer de l'espace disque
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android
          sudo apt-get clean
          df -h

      - name: Exécution du script setup
        shell: bash -l {0}
        run: |
          chmod +x setup.sh
          ./setup.sh

      - name: Nettoyer les caches conda
        shell: bash -l {0}
        run: |
          conda clean -a -y
          rm -rf ~/.conda/pkgs
          rm -rf ~/.cache/pip

      - name: Installer un affichage virtuel pour la GUI
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Lancer les scripts (pipeline)
        shell: bash -l {0}
        run: |
          python ./package/tysserand_network.py --file config.yaml --working_dir ./test/
          python ./package/assortativity.py --file config.yaml --working_dir ./test/
          python ./package/niche_analysis.py --file config.yaml --working_dir ./test/

      - name: Smoke test de l'interface graphique
        shell: bash -l {0}
        run: |
          timeout 10s xvfb-run -a python ./GUI_MOSNA.py || true